name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Ensure all dependencies are installed

      - name: Start FastAPI Server
        env:
          PYTHONPATH: ${{ github.workspace }}  # ✅ Ensures Python finds `api/`
        run: |
          python server.py &  # Run FastAPI server in the background
          sleep 5  # Wait for the server to start

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}  # ✅ Ensures tests can import modules
        run: pytest tests/
